FROM ufoym/deepo:all-py36-jupyter

RUN apt-get update && apt-get install -y vim unzip imagemagick
RUN pip install --upgrade pip
RUN pip install seaborn
RUN pip install chainercv
RUN pip install tqdm
RUN pip install pydicom
RUN pip install kaggle
