FROM kaggle/python

RUN apt-get update && \
		apt-get -y install graphviz
RUN pip install --upgrade pip
RUN pip install pydotplus 
RUN pip install pulp
RUN pip install pycddlib
RUN pip install vpython
RUN pip install cvxopt
RUN pip install picos
