FROM kaggle/python

RUN apt-get update
RUN apt-get -y install graphviz
#RUN apt-get -y install build-essential
#RUN apt-get -y install manpages-dev

RUN pip install --upgrade pip
RUN pip install pydotplus 
RUN pip install pulp
#RUN pip install pycddlib
RUN pip install vpython
RUN pip install cvxopt
RUN pip install picos
